set-option -g prefix `
bind-key -T prefix ` send-prefix

set -g default-terminal 'screen-256color'
set -g base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on
set -g status-style bg='#666666',fg='#aaaaaa'
set -g status-left ''
set -g status-right ''
set -g history-limit 10000
set -g window-status-current-format "#[fg=black,bg=white,bold]#I:#W#F"
set-option -g set-titles on
set-window-option -g automatic-rename on
set -sg escape-time 0

unbind-key C-z
unbind C-b
bind -n S-Left previous-window
bind -n S-Right next-window

if-shell "[ -f ~/.tmux.conf.local ]" 'source ~/.tmux.conf.local'
